record Config(
        long workDurationSec,
        long orderDelayMillis,
        int bakers,
        int couriers,
        int warehouseCapacity,
        int[] bakersSpeed,
        int[] couriersCapacity
) {}